name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Pull the static file
      run: |
        echo "${{ SSH_KEY }}" > ~/.ssh/id_ecdsa
        ssh root@0vo.moe
        cd /root/myservice-docker/www/hugo
        git pull
